[package]
name = "amaranth_commit_msg_hook"
version = "0.1.0"
authors = ["Sean Hutchings <seanhut@yandex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
